name: Generate README Files

# Trigger the workflow on push or pull request to the main branch, or when JSON files change
on:
  push:
    branches:
      - main
    paths:
      - 'dir/**/*.json'
  pull_request:
    branches:
      - main
    paths:
      - 'dir/**/*.json'

jobs:
  generate_readmes:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ensure the Node.js version matches your environment

      # Install dependencies (if any)
      - name: Install Dependencies
        run: npm install

      # Run the script to generate README.md files
      - name: Run README Generator Script
        run: node scripts/generate-readmes.js

      # Commit and push the updated README.md files
      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add dir/**/README.md
          git commit -m "Auto-update README.md files"
          git push
        # Ignore if there are no changes to commit
        continue-on-error: true
